cc_library(
    name = 'vkllama',
    srcs = [],
    hdrs = [],
    deps = ["//src/core:core", "//src/ops:ops"],
    copts = ['-std=c++17'],
    includes = ['./'],
    visibility = ['//visibility:public']
)
