cc_library(
    name = 'llama2',
    srcs = [],
    hdrs = ['llama2.h'],
    deps = ['//models/proto:llama2_model_cc_proto'],
    copts = ['-std=c++17'],
    visibility = ['//visibility:public']
)

cc_library(
    name = 'gguf',
    srcs = ['gguf/gguf.cpp'],
    hdrs = ['gguf/gguf.h'],
    deps = [],
    copts = ['-std=c++17'],
    visibility = ['//visibility:public']
)
