cc_library(
    name = 'llama2',
    srcs = [],
    hdrs = ['llama2.h', 'gguf/gguf.h'],
    deps = ['//models/proto:llama2_model_cc_proto'],
    copts = ['-std=c++17'],
    visibility = ['//visibility:public']
)
